[General]
skip-proxy = localhost, *.local

[Proxy Group]
Apple-AI = select, DIRECT

[Rule]
DOMAIN-SUFFIX,smoot.apple.com,Apple-AI
DOMAIN-SUFFIX,guzzoni.apple.com,Apple-AI
DOMAIN,gspe1-ssl.ls.apple.com,Apple-AI

DOMAIN,mask.icloud.com,Apple-AI
DOMAIN-SUFFIX,mask-h2.icloud.com,Apple-AI
DOMAIN,mask-api.icloud.com,Apple-AI
DOMAIN-SUFFIX,mask-api.fe.apple-dns.net,Apple-AI

DOMAIN,mask.apple-dns.net,Apple-AI
DOMAIN-SUFFIX,mask-t.apple-dns.net,Apple-AI

DOMAIN-SUFFIX,apple-relay.mask.apple-dns.net,Apple-AI
DOMAIN-SUFFIX,gateway.icloud.com,Apple-AI

DOMAIN-SUFFIX,apple-relay.apple.com,Apple-AI
DOMAIN-SUFFIX,apple-relay.akamaized.net,Apple-AI
DOMAIN-SUFFIX,apple-relay.cloudflare.com,Apple-AI
DOMAIN-SUFFIX,apple-relay.fastly-edge.com,Apple-AI

DOMAIN-SUFFIX,apps.mzstatic.com,Apple-AI
DOMAIN-SUFFIX,1s.apple.com,Apple-AI

DOMAIN-SUFFIX,polyfill-fastly.io,Apple-AI
DOMAIN-SUFFIX,cp4.cloudflare.com,Apple-AI

FINAL,DIRECT
