[General]
skip-proxy = localhost, *.local

[Proxy Group]
Apple-AI = select, DIRECT, PROXY

[Rule]
RULE-SET,https://raw.githubusercontent.com/lazh8/Apple-Intelligence-Shadowrocket/main/Apple-Intelligence.list,Apple-AI

FINAL,DIRECT
